language: objective-c
osx_image: xcode12.2
before_install:
  - gem install cocoapods
  - brew update
  - brew outdated carthage || brew upgrade carthage
jobs:
  include:
    - stage: Unit tests iOS
      name: iOS
      script:
      - xcodebuild -project okta-oidc.xcodeproj -scheme "okta-oidc-ios" -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" clean test
    - stage: Unit tests MacOS
      name: MacOS
      script:
      - xcodebuild -project okta-oidc.xcodeproj -scheme "okta-oidc-mac" -destination "platform=macOS" clean test
    - stage: UI tests iOS
      name: iOS
      script:
      - xcodebuild -project okta-oidc.xcodeproj -scheme "okta-oidc" -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" clean test
    - stage: Swift Package Manager validation
      name: MacOS
      script:
      - swift test
    - stage: Cocoapods validation
      name: iOS
      script:
      - pod lib lint --allow-warnings
    - stage: Carthage validation
      name: iOS
      script:
      # Test two workarounds 
      # https://github.com/Carthage/Carthage#getting-started
      - ./scripts/carthage-xcode-12.sh build --no-skip-current
      - carthage build --use-xcframeworks --no-skip-current
